default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
mastodon-green: styles/mastodon-green.scss
mastodon-blue: styles/mastodon-blue.scss
crazynewworld: styles/crazynewworld.scss
crazynewworld-blue: styles/crazynewworld-blue.scss
crazynewworld-sakura: styles/crazynewworld-sakura.scss
crazynewworld-shouwa: styles/crazynewworld-shouwa.scss
crazynewworld-tricolor: styles/crazynewworld-tricolor.scss
crazynewworld2: styles/crazynewworld2.scss
crazynewworld2-blue: styles/crazynewworld2-blue.scss
crazynewworld2-sakura: styles/crazynewworld2-sakura.scss
crazynewworld2-shouwa: styles/crazynewworld2-shouwa.scss
crazynewworld2-tricolor: styles/crazynewworld2-tricolor.scss